### ISSUE TITLE
cuTENSOR 2 migration errors on cuQuantum

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/cuquantum-feedstock#55]
Currently the bot is failing to apply [the cuTENSOR 2 migration]( https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/71db32db7824b0597d65b9611b3fe693c43c1969/recipe/migrations/cutensor2.yaml ) to cuQuantum as it fails the migrator's solvability check. In particular it tries to create an environment with CUDA 11.0, which fails. More details in [this log]( https://github.com/regro/cf-scripts/actions/runs/7660784785/job/20878810689#step:8:21220 ). Have included the relevant snippet below

```
  ['libstdcxx-ng >=12',
   '__glibc >=2.17,<3.0.a0',
   'mpich 4.*',
   'cuda-version 11.0.*',
   'cutensor 2.*',
   'libgcc-ng >=12']
  
  for channels 
  
  ['file:///home/runner/work/_temp/tmpjlsmicf0', 'conda-forge', 'msys2']
  
  The reported errors are:
  
  Could not solve for environment specs
  The following packages are incompatible
  ├─ cuda-version 11.0.*  is installable and it requires
  │  └─ cudatoolkit 11.0|11.0.* , which can be installed;
  └─ cutensor 2.*  is not installable because there are no viable options
     ├─ cutensor 2.0.0.7 would require
     │  └─ cuda-version >=12.0,<13 , which conflicts with any installable versions previously reported;
     └─ cutensor 2.0.0.7 would require
        └─ cudatoolkit >=11.1,<12 , which conflicts with any installable versions previously reported.
```

**Comment by jakirkham** [comment]
Some options to resolve this include:

* Manually applying the migrator (the bot is able to do that much so it should work)
* Disabling the solvability check in the cuTENSOR 2 migrator ( like what we did for CUDA 12: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4525 ) to allow the bot to proceed
* Changing the CUDA version used by the bot to solve to something newer (like CUDA 11.8)

Maybe there are other options outside of these to consider

Please let me know what you think

**Comment by jakirkham** [comment]
cc @leofang

**Comment by leofang** [comment]
Thanks, John. I dropped the ball. I did also notice the error status. The fix is to relax these two lines
https://github.com/conda-forge/cuquantum-feedstock/blob/d21a50c51af96049b43d82971bda690b979a7af8/recipe/meta.yaml#L92
and 
https://github.com/conda-forge/cuquantum-feedstock/blob/d21a50c51af96049b43d82971bda690b979a7af8/recipe/meta.yaml#L174
so that for CUDA 11 we can use 11.8 to build the packages. For some reason that I can't recall now, I hard-wired the minor version `.0`...

**Comment by leofang** [comment]
For context (for those in @conda-forge/cuquantum), what's asked here is not to update to cuTENSOR 2 immediately; instead, the error is the bot is supposed to send a version update migrator to this feedstock (which will fail because we don't support 2.0 yet), but it couldn't because the bot encountered an error that it's not supposed to hit.

**Comment by leofang** [comment]
@conda-forge-admin, please rerender

**Comment by leofang** [comment]
The bot is working now: https://github.com/conda-forge/cuquantum-feedstock/pull/57
